apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
spec:
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-service
    - protocol: TCP
      port: 8081 # Port baru untuk Gin API
      targetPort: 8081 # Port target Gin API di dalam container
      name: gin-service
    - protocol: TCP
      port: 90
      targetPort: 9090
      name: grpc-service
  type: ClusterIP
